### ISSUE TITLE
Migrate from supervosrd to systemd

### ISSUE THREAD

**Issue by josh-padnick** [hashicorp/terraform-google-consul#16]
Now that [Amazon Linux 2](https://aws.amazon.com/amazon-linux-2/) is nearly GA, all major Linux distros now use systemd as the init system. As a result, our use of supervisor to run Consul is a bit outdated. Therefore, we should switch from supervisord to running Consul with systemd.

**Comment by robmorgan** [comment]
I've switched to running Consul (and stopping Consul) with `systemd` in #55. I'm going to close out this issue.
