### ISSUE TITLE
Tiny typo

### ISSUE THREAD

**Issue by floydkots** [hashicorp/terraform-google-consul#22]
Just a [tiny typo](https://github.com/hashicorp/terraform-google-consul/blame/fb9532a01cef5b4fe2a2fdeb1291586059150648/README.md#L40).

Your app can now *usr* the local...

**Comment by josh-padnick** [comment]
Nice catch, although this commit message was from a year ago and the risk of doing a `git force -push` probably outweighs the value of fixing the typo.
