### ISSUE TITLE
network vs subnetwork in the instance_template

### ISSUE THREAD

**Issue by apenney** [hashicorp/terraform-google-consul#4]
Hi,

Not sure of the best way to handle this in Terraform.  We have a custom network which means the template `consul_server_private` breaks in:

  network_interface {
    network = "${var.network_name}"
  }

And needs to be changed to a subnetwork.  Is there a good pattern to handle this?

**Comment by josh-padnick** [comment]
Looks like we may be missing a param that allows you to pass in a subnetwork instead of a network! PRs welcome on this!
