### ISSUE TITLE
Improve rolling update

### ISSUE THREAD

**Issue by kri5** [hashicorp/terraform-google-consul#41]
The `consul-cluster` module makes use of the `update_strategy` attribute to manage how are handled updates.

This is now only present in the `google` provider, and the `google-beta` provider defines a new attribute called `update_policy` that seems to allow a more fine grained way of doing rolling updates (maxSurge, minAvailable, etc.)

I do not know if there is a way for both theses features to co-exist in the module, using an opt-in attributes or something similar, as it would be great to move to this `update_policy` feature, but some people might want to make use of `stable` only features.

Any advices?

**Comment by kri5** [comment]
Retrying this, it seems now that the field `update_strategy` has been deprecated in the stable google provider

`Warning: "update_strategy": [DEPRECATED] This field is removed.`

But i do not see any alternative in the stable provider.

Should the module use the beta provider for this usage meanwhile?

**Comment by josh-padnick** [comment]
We've found that with GCP it's necessary to mix and match stable and beta resources. See [our own example](https://github.com/gruntwork-io/terraform-google-gke/blob/master/examples/gke-public-cluster/main.tf#L17-L27) with our GKE Terraform module.

I'd advise taking that same approach here!

**Comment by kri5** [comment]
@josh-padnick i've made some draft PR here #47 

Feel free to comment.

**Comment by robmorgan** [comment]
I've implemented this functionality in #55, updated the documentation, and also included the necessary tests. I'll close out this issue.
