### ISSUE TITLE
terraform apply not idempotent

### ISSUE THREAD

**Issue by tpdownes** [hashicorp/terraform-google-consul#50]
A successful `terraform apply` followed immediately by `terraform apply` should result in no actions being proposed. The use of `name_prefix` in [2 locations within the the consul-cluster](https://github.com/hashicorp/terraform-google-consul/blob/master/modules/consul-cluster/main.tf#L107) module causes the instance template to be unnecessarily modified on the 2nd and all subsequent runs. Root issue: a timestamp is appended to the prefix and, of course, time marches on.

I believe this could be fixed by switching from `name-prefix` to `name` with a dynamically generated name that is stored in tfstate. e.g.

```
provider "random" {
  version = "~> 2.2.1"
}
...
resource "random_pet" "example" {}
...
resource "google_compute_instance_template" "consul_server_private" {
...
  name = "${var.cluster_name}-${random_pet.example.id}"
...
}
...
resource "google_compute_instance_template" "consul_server_public" {
...
  name = "${var.cluster_name}-${random_pet.example.id}"
...
}
```
There are a [number of other options](https://www.terraform.io/docs/providers/random/index.html) besides "pet names" which are of the form "wascally-wabbit". I'll put together a PR if one is welcome.

**Comment by robmorgan** [comment]
I've removed the `template_file` workaround in #55 and I believe this fixes this issue.
