### ISSUE TITLE
Error: this field cannot be set / required field is not set

### ISSUE THREAD

**Issue by Leshii82** [hashicorp/terraform-google-consul#52]
Hey guys,
I'm using your module of "consul-cluster" to create it with terragrunt.
And having 2 errors - 

> Error: "instance_template": this field cannot be set
> 
>   on main.tf line 16, in resource "google_compute_region_instance_group_manager" "consul_server":
>   16: resource "google_compute_region_instance_group_manager" "consul_server" {
> 
> 
> 
> Error: "version": required field is not set
> 
>   on main.tf line 16, in resource "google_compute_region_instance_group_manager" "consul_server":
>   16: resource "google_compute_region_instance_group_manager" "consul_server" {

I saw in Terraform documentation, that version for example, is required, but it missing in your module.
Any help/suggestion for both error?

Thanks in advance!

**Comment by nimajalali** [comment]
This is fixed in #49

**Comment by robmorgan** [comment]
Implemented a fix in #55 based on #49 and including updates for TF 0.12.
